import './globals.css'

import { Inter } from 'next/font/google'
import Header from './components/Header';
import Hero from './hero';
import Skeleton, { SkeletonTheme } from 'react-loading-skeleton';


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Movie Search App ',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Header />
        <main>{children}</main>
      </body>
    </html>
  )
}
